People/Controllers/ContactUsController.cs
using System.Web.Mvc;

namespace People.Controllers
{
    public class ContactUsController : Controller
    {
        //
        // GET: /Terms/

        public ActionResult Index()
        {
            return View();
        }

    }
}

People/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace People.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lolp(string pop,int? page)
        {
            return View("Lolp",(object)pop);
        }
        
        public ActionResult ChindiMaga(string pop,int? page,string returnurl)
        {
            var action = Url.Action("ChindiMaga", new {retururL = "loda"});
            return View("Lolp",(object)action);
        }

    }
    public class BobModel
    {
        public string Mamu;
        public string Maga;
    }
}

People/Controllers/TermsController.cs
using System.Web.Mvc;

namespace People.Controllers
{
    public class TermsController : Controller
    {
        //
        // GET: /Terms/

        public ActionResult Index()
        {
            return View();
        }

    }
}

People/Controllers/UrlController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web.Mvc;
using DAL.FNhibernate.Entities;
using DAL.FNhibernate.Repositories;
using Logic.Services;
using Microsoft.Security.Application;
using Microsoft.Web.Helpers;
using People.Attributes;
using People.Models;
using System.Linq;
using People.Utility;

namespace People.Controllers
{
    public class UrlController : Controller
    {
        private IUrlRepository urlRepository;
        private IPostRepository postRepository;
        private readonly IUserRepository userRepository;
        private readonly ICommentsRepository commentsRepository;
        private readonly IHostHeaderService hostHeaderService;
        readonly string domainName = ConfigurationManager.AppSettings["DomanName"];
        readonly string privateKey = ConfigurationManager.AppSettings["RecaptchaPrivateKey"];
        readonly string websiteName = ConfigurationManager.AppSettings["SiteName"];

        public UrlController(IUrlRepository urlRepository, IPostRepository postRepository, IUserRepository userRepository,
            ICommentsRepository commentsRepository, IHostHeaderService hostHeaderService)
        {
            this.urlRepository = urlRepository;
            this.postRepository = postRepository;
            this.userRepository = userRepository;
            this.commentsRepository = commentsRepository;
            this.hostHeaderService = hostHeaderService;
        }

        public ActionResult Index(string id)
        {
            //todo: parse for special characters here 
            var url = urlRepository.GetUrlWithPost(id);

            if (url != null && url.Posts != null)
            {
                var posts = url.Posts;
                ViewBag.IsAdminOrOwner = posts.UserProfile.UserName == User.Identity.Name;
                ViewBag.Title = id;
                url.Hits++;
                ViewBag.Hits = url.Hits;
                return View(posts);
            }
            ViewBag.DomainName = domainName;
            return View("PageNotFound");
        }

        public ActionResult IframeBody(int id)
        {
            var posts = postRepository.GetPost(id);
            return View("Iframe", (object)posts.Body);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.DomainNameWithDot = "." + domainName;
            return View(new PostsViewModel());
        }
        
        [ValidateInput(false)]
        [Authorize]
        [HttpPost]
        public ActionResult Create(PostsViewModel postsViewModel)
        {
            ViewBag.DomainNameWithDot = "." + domainName;
            var isCaptchaValid = ReCaptcha.Validate(privateKey);
            if (ModelState.IsValid && isCaptchaValid)
            {
                UserProfile userProfile = userRepository.GetUser(User.Identity.Name);
                string subDomain = postsViewModel.Subdomain;
                var url = urlRepository.GetUrl(subDomain);
                if (url != null)
                {
                    ModelState.AddModelError("subDomainChosen", "Subdomain already taken, please choose another");
                    return View(postsViewModel);
                }
//                    var fullSubdomainWithPostfix = subDomain + "." + websiteName + ".com";
                var posts = new Posts
                    {
                        Body = HtmlUtility.Instance.SanitizeHtml(postsViewModel.Body),
                        Title = HtmlUtility.Instance.SanitizeHtml(postsViewModel.Title),
                        Samay = DateTime.UtcNow,
                        Commentable = postsViewModel.Commentable,
                        ShowHits = postsViewModel.ShowHits,
                        UserProfile = userProfile,
                        Url = subDomain
                    };
//                    hostHeaderService.AddHostHeader(websiteName, fullSubdomainWithPostfix);

                var urlMapping = new UrlMapping
                {
                    Url = subDomain,
                    Posts = posts
                };
                urlRepository.Save(urlMapping);
                return Redirect("http://" + subDomain + "." + domainName);    
            }
            return View(postsViewModel);
        }

        public JsonResult IsDomainFree(string Id)
        {
            if (string.IsNullOrEmpty(Id))
            {
                return null;
            }
            var urlMapping = urlRepository.GetUrl(Id);
            if (urlMapping == null)
            {
                return Json(new { isFree = true });
            }
            return Json(new { isFree = false });
        }

        [MyPostUserAuthorization]
        [HttpPost]
        public JsonResult Delete(int id)
        {
            Posts post = postRepository.GetPost(id);
            UrlMapping urlWithPost = urlRepository.GetUrlWithPost(post);
            
//            string subDomain = urlWithPost.Url;

            urlRepository.Delete(urlWithPost);
            
//            var fullSubdomainWithPostfix = subDomain + "." + websiteName + ".com";
//            hostHeaderService.RemoveHostHeader(websiteName, fullSubdomainWithPostfix);

            return Json(new { success = true });
        }

        [HttpPost]
        public JsonResult DelteComment(int id)
        {
            Comments commentsWithPost = commentsRepository.GetCommentsWithPost(id);
            if (commentsWithPost == null)
            {
                return Json(new
                    {
                        IsSuccess = false,
                        Id = id,
                        Message = "Comment already deleted"
                    });
            }
            if (commentsWithPost.Posts.UserProfile.UserName == User.Identity.Name)
            {
                commentsRepository.Delete(commentsWithPost);
                return Json(new
                {
                    IsSuccess = true,
                    Id = id
                });    
            }
            return Json(new
                {
                    error = "You're not authorised to delete Comments"
                });
        }

        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Comments(CommentsModel comments)
        {
            var isCaptchaValid = ReCaptcha.Validate(privateKey);
            if (ModelState.IsValid && isCaptchaValid)
            {
                Posts post = postRepository.GetPost(comments.PostId);
                if (post == null)
                {
                    return RedirectToAction("Index");
                }
                post.Comments.Add(new Comments
                {
                    Body = HtmlUtility.Instance.SanitizeHtml(comments.Body),
                    Email = comments.Email,
                    Name = comments.Name,
                    Samay = DateTime.UtcNow,
                    Posts = post
                });
                postRepository.Save(post);
                return Redirect(HttpContext.Request.UrlReferrer.AbsoluteUri);
            }
            string errors = string.Join(@"<br \>", ModelState.Values
                                                        .SelectMany(x => x.Errors)
                                                        .Select(x => x.ErrorMessage));
            if (!isCaptchaValid)
            {
                errors = string.Join(@"<br \>",
                                 "The characters you entered donot match the one in image. Please try again ..");    
            }
            
            return Json(new
                {
                    errors
                });
        }

        [HttpGet]
        [MyPostUserAuthorization]
        public ActionResult Edit(int id)
        {
            ViewBag.DomainNameWithDot = "." + domainName;
            Posts posts = postRepository.GetPost(id);
            if (posts!=null)
            {
                var postsViewModel = new PostsViewModel
                {
                    Body = posts.Body,
                    Id = posts.Id,
                    Commentable = posts.Commentable,
                    Subdomain = posts.Url,
                    Title = posts.Title
                };
                return View(postsViewModel);    
            }
            return View("AccessDenied");
        }

        [ValidateInput(false)]
        [MyPostUserAuthorization]
        [HttpPost]
        public ActionResult Edit(PostsViewModel postsModel)
        {
            if (ModelState.IsValid)
            {
                Posts post = postRepository.GetPost(postsModel.Id);
                string url = urlRepository.GetUrlForPost(post);
                //todo: plzz do some sql injection and spl characters checks ?? If you don't fix this and go to prod, you will be screwed ! SCREWED !
                post.Body = HtmlUtility.Instance.SanitizeHtml(postsModel.Body);
                post.Title = HtmlUtility.Instance.SanitizeHtml(postsModel.Title);
                post.Commentable = postsModel.Commentable;
                post.ShowHits = postsModel.ShowHits;
                postRepository.Save(post);

                return Redirect("http://" + url + "." + domainName);
            }
            return View(postsModel);
        }
    }
}

People/Views/Home/Index.cshtml
@using System.Configuration
@{
    ViewBag.Title = "is An Asshole | isAnAsshole";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<script src="@Url.Content("~/Scripts/urlmapping.js")" type="text/javascript"> </script>
<div id="wrap">
    <div id = "main" class="container text-center">
        <h1> Welcome to "Is an Asshole" </h1>
@*        <h2>Had a bad day with annoying people ?</h2>*@
@*        <h3> we've been there too ..</h3>*@
@*        <h4>You can now vent it out here !</h4> *@
        <h3>More often than not, the world forces you to endure some of the most annoying people around. It could be your co-worker on a daily basis <a target="_blank" href="http://kengodoy.isanasshole.com">(Ken is an Asshole)</a>
            or that ocassional guy on TV <a target="_blank" href="http://ricksantelli.isanasshole.com">(Rick is an Asshole)</a> or a bully at school or <b>an asshole</b> driving on the road</h3>
        <h4>How do you deal with these <i>assholes</i> ?? 
            One way we know is to bitch about them on the internet and see what the world thinks of 'em.
             Here's a platform that helps you do the same by creating a site against them. </h4>
@*        <h4>Create a site against them and tell the world all about it </h4>*@
        <h4 class="orange"> No Sign Up required </h4>
        <br/>
        @{
            string domainName = ConfigurationManager.AppSettings["DomanName"];
        }
        <b class="blue"><input type="text" class="text-center" style="font-weight: bold; color: #2B60DE; "/>.@domainName</b>
        <div>
            @*        @Html.ActionLink("Create Website"+ "<br />" + "No SignUp Required", "Create", "Url",new {},new {@class="btn btn-primary btn-large blocky"})*@
            <a href="@Url.Action("Create","Url")" class="btn btn-primary btn-large">Create Website
            </a>
        </div>
        <br/>
        <br/>
        <div>
            <img src="~/Content/img/is an asshole.png" alt="Is an Asshole"/>
        </div>
    </div>
</div>
<footer class="navbar navbar-fixed-bottom text-center ">
        @Html.ActionLink("Privacy","Index","Privacy",null,new {@class = "whitish_footer FontSmall"}) &nbsp; &nbsp;
        @Html.ActionLink("Terms Of Service","Index","Terms",null,new {@class = "whitish_footer FontSmall"})  &nbsp; &nbsp;
        @Html.ActionLink("Contact Us","Index","ContactUs",null,new {@class = "whitish_footer FontSmall"})
</footer>

People/Views/Home/Lolp.cshtml
@model string

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <title>Lolp</title>
    </head>
    <body>
        <div>
            lolp   
            @if(Model!=null)
            {
                @Model
            }
        </div>
    </body>
</html>